// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package id.fajrin.javax;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }

//     private void assertNotNull(String greeting, String string) {
//         // TODO Auto-generated method stub
//         throw new UnsupportedOperationException("Unimplemented method 'assertNotNull'");
//     }
// }
