/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tuprak9;


import java.util.HashMap;
import java.util.Map;

import javafx.animation.PauseTransition;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.stage.Stage;
import javafx.util.Duration;

public class App extends Application {
    private Map<String, String> userAcces = new HashMap<>();
    private Map<String, String> userProfiles = new HashMap<>();
    private String inputUname;
    private String inputPass;
    private String inputNama;
    private String inputUltah;
    private String inputHoby;
    private String userLogin; 
    private String inputAlamat;

    @Override
    public void start(Stage stage) throws Exception {
        stage.setScene(mainScene(stage));
        stage.setTitle("Zul Punya");
        stage.setResizable(false);
        stage.show();
    }


    private Scene mainScene(Stage stage) {
        Label judul = new Label("            Helow...\n Welcome to This Application");
        judul.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 35));
        judul.setTextFill(Color.web("#AEDF66"));
        judul.setAlignment(Pos.BASELINE_LEFT);
        judul.setPadding(new Insets(100, 0, 0, 130));

        Label adaAkun = new Label("Already have an account?");
        adaAkun.setFont(Font.font("Arial", FontWeight.BOLD, 15));
        adaAkun.setTextFill(Color.web("#AEDF66"));
        adaAkun.setAlignment(Pos.BASELINE_LEFT);
        adaAkun.setPadding(new Insets(50, 0, 0, 280));

        Label takdeAkun = new Label("Don't have an account?");
        takdeAkun.setFont(Font.font("Arial", FontWeight.BOLD, 15));
        takdeAkun.setTextFill(Color.web("#AEDF66"));
        takdeAkun.setAlignment(Pos.BASELINE_LEFT);
        takdeAkun.setPadding(new Insets(110, 0, 0, 290));

        Button btnReg = new Button("Register");
        btnReg.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnReg.setPrefWidth(150);
        btnReg.relocate(295, 400);
        btnReg.setOnAction(e -> stage.setScene(regScene(stage)));

        Button btnLog = new Button("Log in");
        btnLog.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnLog.setPrefWidth(150);
        btnLog.relocate(295, 275);
        btnLog.setOnAction(e -> stage.setScene(logScene(stage)));

        Image bgImage = new Image(getClass().getResourceAsStream("/foto/bg1.jpg"));
        ImageView viewBgImage = new ImageView(bgImage);
        viewBgImage.setPreserveRatio(true);
        viewBgImage.setFitWidth(740);
        viewBgImage.setFitHeight(580);

        // icon aplikasi
        Image imageIcon = new Image(getClass().getClassLoader().getResourceAsStream("foto/logo.jpg"));
        if (imageIcon.isError()) {
            System.out.println("Failed to load application icon.");
        } else {
            stage.getIcons().add(imageIcon);
        }

        VBox vbox = new VBox(0, judul, adaAkun, takdeAkun);
        vbox.setAlignment(Pos.TOP_LEFT);

        Pane root = new Pane();
        root.getChildren().addAll(viewBgImage, vbox, btnReg, btnLog );
        Scene scene = new Scene(root, 740, 580);
        return scene;
    }

    private Scene regScene(Stage stage) {
        Label regJudul = new  Label("Register");
        regJudul.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 30));
        regJudul.setTextFill(Color.web("#AEDF66"));
        regJudul.setAlignment(Pos.BASELINE_LEFT);
        regJudul.setPadding(new Insets(20, 0, 0, 310));

        // Registrasi
        Label pass = new Label("Password\t:");
        pass.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        pass.setTextFill(Color.web("#AEDF66"));
        pass.setAlignment(Pos.BASELINE_LEFT);
        pass.setPadding(new Insets(20, 0, 0, 150));
        
        TextField fieldPass = new TextField();
        fieldPass.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldPass.setPrefWidth(290);
        fieldPass.setMaxWidth(290);
        // fieldPass.relocate(300, 155);

        Label uname = new Label("Username\t:");
        uname.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        uname.setTextFill(Color.web("#AEDF66"));
        uname.setAlignment(Pos.BASELINE_LEFT);
        uname.setPadding(new Insets(50, 0, 0, 150));
 
        TextField fieldUname = new TextField();
        fieldUname.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldUname.setPrefWidth(290);
        fieldUname.setMaxWidth(290);


        Label urProfil = new  Label("Your Profil ^.^");
        urProfil.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 30));
        urProfil.setTextFill(Color.web("#AEDF66"));
        urProfil.setAlignment(Pos.BASELINE_LEFT);
        urProfil.setPadding(new Insets(50, 0, 0, 100));

        // Data Profil
        Label nama = new Label("Name\t\t:");
        nama.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        nama.setTextFill(Color.web("#AEDF66"));
        nama.setAlignment(Pos.BASELINE_LEFT);
        nama.setPadding(new Insets(30, 0, 0, 150));

        TextField fieldNama = new TextField();
        fieldNama.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldNama.setPrefWidth(290);
        fieldNama.setMaxWidth(290);

        Label ultah = new Label("Date of Birth\t:");
        ultah.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        ultah.setTextFill(Color.web("#AEDF66"));
        ultah.setAlignment(Pos.BASELINE_LEFT);
        ultah.setPadding(new Insets(20, 0, 0, 150));

        TextField fieldUltah = new TextField();
        fieldUltah.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldUltah.setPrefWidth(290);
        fieldUltah.setMaxWidth(290);

        Label hoby = new Label("Hobby\t\t:");
        hoby.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        hoby.setTextFill(Color.web("#AEDF66"));
        hoby.setAlignment(Pos.BASELINE_LEFT);
        hoby.setPadding(new Insets(20, 0, 0, 150));

        TextField fieldHoby = new TextField();
        fieldHoby.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldHoby.setPrefWidth(290);
        fieldHoby.setMaxWidth(290);

        Label alamat = new Label("Alamat\t\t:");
        alamat.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        alamat.setTextFill(Color.web("#AEDF66"));
        alamat.setAlignment(Pos.BASELINE_LEFT);
        alamat.setPadding(new Insets(20, 0, 0, 150));

        TextField fieldAlamat = new TextField();
        fieldAlamat.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldAlamat.setPrefWidth(290);
        fieldAlamat.setMaxWidth(290);

        Label catatan = new Label();
        catatan.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 15));
        catatan.setTextFill(Color.web("#AEDF66"));
        catatan.setAlignment(Pos.BASELINE_LEFT);
        catatan.relocate(450, 470);
        
        Button btnSubmit = new Button("Submit");
        btnSubmit.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnSubmit.setPrefWidth(150);
        btnSubmit.relocate(450, 490);
        btnSubmit.setOnAction(e -> {
            inputUname = fieldUname.getText();
            inputPass = fieldPass.getText();
            inputNama = fieldNama.getText();
            inputUltah = fieldUltah.getText();
            inputHoby = fieldHoby.getText();
            inputAlamat = fieldAlamat.getText();

            if (inputUname.isEmpty() || inputPass.isEmpty() || inputNama.isEmpty() || inputUltah.isEmpty() || inputHoby.isEmpty()) {
                catatan.setText("Please fill in all data");
            } else if (inputPass.length() < 6 ) {
                catatan.setText("Password must be at least 6 characters");
                catatan.relocate(360, 470);
            } else {
                userAcces.put(inputUname, inputPass);
                String profileDetails = inputNama + ", Date of Birth\t: " + inputUltah + ", Hobby\t\t: " + inputHoby + ", Alamat\t\t: " + inputAlamat;
                userProfiles.put(inputUname, profileDetails);
                catatan.setText("Registration successful!");
                catatan.relocate(236, 455);
                catatan.setPadding(new Insets(10, 0, 0, 200));
                PauseTransition pause = new PauseTransition(Duration.seconds(3));
                pause.setOnFinished(event -> {
                // Berpindah ke Scene Kedua setelah 3 detik
                stage.setScene(mainScene(stage));
                });
                pause.play();
            }
        });

        Button btnBack = new Button("Back");
        btnBack.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnBack.setPrefWidth(150);
        btnBack.relocate(140, 490);
        btnBack.setOnAction(e -> stage.setScene(mainScene(stage)));


        Image bgImage = new Image(getClass().getResourceAsStream("/foto/bg1.jpg"));
        ImageView viewBgImage = new ImageView(bgImage);
        viewBgImage.setPreserveRatio(true);
        viewBgImage.setFitWidth(740);
        viewBgImage.setFitHeight(580);

        VBox vbox = new VBox(0, regJudul, uname, fieldUname,  pass, fieldPass, urProfil, nama, fieldNama, ultah, fieldUltah, hoby,  fieldHoby, alamat, fieldAlamat/*judul, adaAkun, takdeAkun */);
        vbox.setAlignment(Pos.TOP_LEFT);
        VBox.setMargin(fieldUname, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldPass, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldNama, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldUltah, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldHoby, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldAlamat, new Insets(-23, 0, 0, 300));

        Pane root = new Pane();
        root.getChildren().addAll(viewBgImage, btnBack, catatan, btnSubmit, vbox);
        Scene scene = new Scene(root, 740, 580);
        return scene;
    }



    private Scene logScene(Stage stage) {
        Label wb = new Label("Welcome Back >,<");
        wb.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 30));
        wb.setTextFill(Color.web("#AEDF66"));
        wb.setAlignment(Pos.BASELINE_LEFT);
        wb.setPadding(new Insets(70, 0, 0, 240));

        Label logJudul = new  Label("Login");
        logJudul.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 30));
        logJudul.setTextFill(Color.web("#AEDF66"));
        logJudul.setAlignment(Pos.BASELINE_LEFT);
        logJudul.setPadding(new Insets(30, 0, 0, 335));

        Label unameLog = new Label("Username\t:");
        unameLog.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        unameLog.setTextFill(Color.web("#AEDF66"));
        unameLog.setAlignment(Pos.BASELINE_LEFT);
        unameLog.setPadding(new Insets(50, 0, 0, 150));
 
        TextField fieldUnameLog = new TextField();
        fieldUnameLog.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldUnameLog.setPrefWidth(290);
        fieldUnameLog.setMaxWidth(290);

        Label passLog = new Label("Password\t:");
        passLog.setFont(Font.font("Arial", FontWeight.BOLD, 20));
        passLog.setTextFill(Color.web("#AEDF66"));
        passLog.setAlignment(Pos.BASELINE_LEFT);
        passLog.setPadding(new Insets(20, 0, 0, 150));
        
        TextField fieldPassLog = new TextField();
        fieldPassLog.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: black; -fx-border-color: #65962C; -fx-border-radius: 5;");
        fieldPassLog.setPrefWidth(290);
        fieldPassLog.setMaxWidth(290);

        Label catatanLog = new Label();
        catatanLog.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 17));
        catatanLog.setTextFill(Color.web("#AEDF66"));
        catatanLog.setAlignment(Pos.BASELINE_LEFT);
        catatanLog.relocate(405, 370);

        Button btnLogin = new Button("Login");
        btnLogin.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnLogin.setPrefWidth(150);
        btnLogin.relocate(450, 400);
        btnLogin.setOnAction(e -> {
            String inputUname = fieldUnameLog.getText();
            String inputPass = fieldPassLog.getText();

            if (userAcces.containsKey(inputUname) && userAcces.get(inputUname).equals(inputPass)) {
                userLogin = inputUname;
                stage.setScene(profileScene(stage));
            } else {
                catatanLog.setText("Invalid username or password");
            }
        });

        Button btnBack = new Button("Back");
        btnBack.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnBack.setPrefWidth(150);
        btnBack.relocate(140, 400);
        btnBack.setOnAction(e -> stage.setScene(mainScene(stage)));

        Image bgImage = new Image(getClass().getResourceAsStream("/foto/bg1.jpg"));
        ImageView viewBgImage = new ImageView(bgImage);
        viewBgImage.setPreserveRatio(true);
        viewBgImage.setFitWidth(740);
        viewBgImage.setFitHeight(580);

        VBox vbox = new VBox(0, wb, logJudul, unameLog, fieldUnameLog, passLog, fieldPassLog);
        vbox.setAlignment(Pos.TOP_LEFT);
        VBox.setMargin(fieldUnameLog, new Insets(-23, 0, 0, 300));
        VBox.setMargin(fieldPassLog, new Insets(-23, 0, 0, 300));

        Pane root = new Pane();
        root.getChildren().addAll(viewBgImage, vbox, catatanLog, btnBack, btnLogin);
        Scene scene = new Scene(root, 740, 580);
        return scene;
    }

    private Scene profileScene(Stage stage) {
        Label profil = new Label("Your Profil >,>");
        profil.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 30));
        profil.setTextFill(Color.web("#AEDF66"));
        profil.setAlignment(Pos.BASELINE_LEFT);
        profil.setPadding(new Insets(80, 0, 0, 260));

        String[] detailProfile = userProfiles.get(userLogin).split(", ");

        Label outputNama = new Label("Name\t\t: " + detailProfile[0]);
        outputNama.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 25));
        outputNama.setTextFill(Color.web("#AEDF66"));
        outputNama.setAlignment(Pos.BASELINE_LEFT);
        outputNama.relocate(150, 180);

        Label outputultah = new Label("" + detailProfile[1]);
        outputultah.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 25));
        outputultah.setTextFill(Color.web("#AEDF66"));
        outputultah.setAlignment(Pos.BASELINE_LEFT);
        outputultah.relocate(150, 230);

        Label outputHoby = new Label("" + detailProfile[2]);
        outputHoby.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 25));
        outputHoby.setTextFill(Color.web("#AEDF66"));
        outputHoby.setAlignment(Pos.BASELINE_LEFT);
        outputHoby.relocate(150, 280);

        Label ouputAlamat = new Label("" + detailProfile[3]);
        ouputAlamat.setFont(Font.font("Comic Sans MS", FontWeight.BOLD, 25));
        ouputAlamat.setTextFill(Color.web("#AEDF66"));
        ouputAlamat.setAlignment(Pos.BASELINE_LEFT);
        ouputAlamat.relocate(150, 330);


        Button btnBack = new Button("Back");
        btnBack.setStyle("-fx-background-color: #D4D4D4; -fx-text-fill: #65962C; -fx-font-weight: bold; -fx-font-size: 18;");
        btnBack.setPrefWidth(150);
        btnBack.relocate(295, 400);
        btnBack.setOnAction(e -> stage.setScene(mainScene(stage)));

        Image bgImage = new Image(getClass().getResourceAsStream("/foto/bg2.jpg"));
        ImageView viewBgImage = new ImageView(bgImage);
        viewBgImage.setPreserveRatio(true);
        viewBgImage.setFitWidth(740);
        viewBgImage.setFitHeight(580);

        VBox vbox = new VBox(0, profil);
        vbox.setAlignment(Pos.TOP_LEFT);

        Pane root = new Pane();
        root.getChildren().addAll(viewBgImage, outputNama, outputultah, outputHoby, ouputAlamat, btnBack, vbox);
        Scene scene = new Scene(root, 740, 580);
        return scene;
    }

    public static void main(String[] args) {
        launch();
    }
}