/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tugaspraktikum9;


import javafx.application.Application;
import javafx.stage.Stage;
import tugaspraktikum9.config.DbConnect;


class AppTest extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        DbConnect.Connection();


    }
    public static void main(String[] args) {
        launch();
    }
}
